<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fn</string>
	</array>
	<key>name</key>
	<string>Fn</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#[^
]*
</string>
			<key>name</key>
			<string>comment.fn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+(\.[0-9]+)?</string>
			<key>name</key>
			<string>constant.numeric.fn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.fn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.fn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|\-|\*|\/)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.fn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.fn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(eq)</string>
			<key>name</key>
			<string>keyword.operator.comparison.fn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.builtin.fn</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in functions</string>
			<key>match</key>
			<string>\b(not|import|import!|print)[\b]?\(</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.</string>
			<key>name</key>
			<string>punctuation.definition.dot.fn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.fn</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.fn</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Assignment</string>
			<key>match</key>
			<string>(\w+) ?(=) </string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(when)\b</string>
			<key>name</key>
			<string>keyword.control.fn</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\w+)\b(?=\()</string>
			<key>name</key>
			<string>entity.function.fn</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.fn</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function Definition</string>
			<key>match</key>
			<string>fn \(([\w, ]+)\) ?\{</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fn</string>
	<key>uuid</key>
	<string>074ae84d-9a4d-4e7d-b171-a117e9cae98d</string>
</dict>
</plist>
